[run]
skip-files = [
    #"source/reqs_test.go",
]

[linters]
enable = [
	"errcheck",
	"gosimple",
	"govet",
	"ineffassign",
	"staticcheck",
	"unused",

	"asciicheck",
	"bidichk",
	"bodyclose",
	"containedctx",
	"contextcheck",
	"cyclop",
	"decorder",
	"dogsled",
	"dupl",
	"dupword",
	"durationcheck",
	# "errchkjson",
	"errname",
	"errorlint",
	"revive",
]

#[linters-settings.revive]
#enable-all-rules = true

[[linters-settings.revive.rules]]
name = "var-declaration"
disabled = true

[[linters-settings.revive.rules]]
name = "line-length-limit"
disabled = false
