// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: reqs2http/v1/header.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *CustomHeader) Reset() {
	*x = CustomHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reqs2http_v1_header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomHeader) ProtoMessage() {}

func (x *CustomHeader) ProtoReflect() protoreflect.Message {
	mi := &file_reqs2http_v1_header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomHeader.ProtoReflect.Descriptor instead.
func (*CustomHeader) Descriptor() ([]byte, []int) {
	return file_reqs2http_v1_header_proto_rawDescGZIP(), []int{0}
}

func (x *CustomHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CustomHeader) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type HeaderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Item:
	//
	//	*HeaderItem_Custom
	//	*HeaderItem_ContentType
	Item isHeaderItem_Item `protobuf_oneof:"item"`
}

func (x *HeaderItem) Reset() {
	*x = HeaderItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reqs2http_v1_header_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderItem) ProtoMessage() {}

func (x *HeaderItem) ProtoReflect() protoreflect.Message {
	mi := &file_reqs2http_v1_header_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderItem.ProtoReflect.Descriptor instead.
func (*HeaderItem) Descriptor() ([]byte, []int) {
	return file_reqs2http_v1_header_proto_rawDescGZIP(), []int{1}
}

func (m *HeaderItem) GetItem() isHeaderItem_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (x *HeaderItem) GetCustom() *CustomHeader {
	if x, ok := x.GetItem().(*HeaderItem_Custom); ok {
		return x.Custom
	}
	return nil
}

func (x *HeaderItem) GetContentType() string {
	if x, ok := x.GetItem().(*HeaderItem_ContentType); ok {
		return x.ContentType
	}
	return ""
}

type isHeaderItem_Item interface {
	isHeaderItem_Item()
}

type HeaderItem_Custom struct {
	Custom *CustomHeader `protobuf:"bytes,1,opt,name=custom,proto3,oneof"`
}

type HeaderItem_ContentType struct {
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3,oneof"`
}

func (*HeaderItem_Custom) isHeaderItem_Item() {}

func (*HeaderItem_ContentType) isHeaderItem_Item() {}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*HeaderItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reqs2http_v1_header_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_reqs2http_v1_header_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_reqs2http_v1_header_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetItems() []*HeaderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_reqs2http_v1_header_proto protoreflect.FileDescriptor

var file_reqs2http_v1_header_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x65, 0x71, 0x73, 0x32, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65, 0x71,
	0x73, 0x32, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x32, 0x0a, 0x0c, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x6f, 0x0a,
	0x0a, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x34, 0x0a, 0x06, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65,
	0x71, 0x73, 0x32, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x12, 0x23, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x38,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x71, 0x73, 0x32, 0x68,
	0x74, 0x74, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6b, 0x61, 0x6e, 0x6f, 0x72, 0x69, 0x79,
	0x61, 0x6e, 0x61, 0x67, 0x69, 0x74, 0x61, 0x6e, 0x69, 0x2f, 0x67, 0x6f, 0x2d, 0x72, 0x65, 0x71,
	0x73, 0x32, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reqs2http_v1_header_proto_rawDescOnce sync.Once
	file_reqs2http_v1_header_proto_rawDescData = file_reqs2http_v1_header_proto_rawDesc
)

func file_reqs2http_v1_header_proto_rawDescGZIP() []byte {
	file_reqs2http_v1_header_proto_rawDescOnce.Do(func() {
		file_reqs2http_v1_header_proto_rawDescData = protoimpl.X.CompressGZIP(file_reqs2http_v1_header_proto_rawDescData)
	})
	return file_reqs2http_v1_header_proto_rawDescData
}

var file_reqs2http_v1_header_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_reqs2http_v1_header_proto_goTypes = []interface{}{
	(*CustomHeader)(nil), // 0: reqs2http.v1.CustomHeader
	(*HeaderItem)(nil),   // 1: reqs2http.v1.HeaderItem
	(*Header)(nil),       // 2: reqs2http.v1.Header
}
var file_reqs2http_v1_header_proto_depIdxs = []int32{
	0, // 0: reqs2http.v1.HeaderItem.custom:type_name -> reqs2http.v1.CustomHeader
	1, // 1: reqs2http.v1.Header.items:type_name -> reqs2http.v1.HeaderItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reqs2http_v1_header_proto_init() }
func file_reqs2http_v1_header_proto_init() {
	if File_reqs2http_v1_header_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reqs2http_v1_header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reqs2http_v1_header_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reqs2http_v1_header_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_reqs2http_v1_header_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*HeaderItem_Custom)(nil),
		(*HeaderItem_ContentType)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reqs2http_v1_header_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reqs2http_v1_header_proto_goTypes,
		DependencyIndexes: file_reqs2http_v1_header_proto_depIdxs,
		MessageInfos:      file_reqs2http_v1_header_proto_msgTypes,
	}.Build()
	File_reqs2http_v1_header_proto = out.File
	file_reqs2http_v1_header_proto_rawDesc = nil
	file_reqs2http_v1_header_proto_goTypes = nil
	file_reqs2http_v1_header_proto_depIdxs = nil
}
