// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: reqs2http/v1/request.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method Method  `protobuf:"varint,1,opt,name=method,proto3,enum=reqs2http.v1.Method" json:"method,omitempty"`
	Url    string  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Header *Header `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Body   []byte  `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reqs2http_v1_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_reqs2http_v1_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_reqs2http_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_METHOD_UNSPECIFIED
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_reqs2http_v1_request_proto protoreflect.FileDescriptor

var file_reqs2http_v1_request_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x65, 0x71, 0x73, 0x32, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65,
	0x71, 0x73, 0x32, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x72, 0x65, 0x71, 0x73,
	0x32, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x72, 0x65, 0x71, 0x73, 0x32, 0x68, 0x74, 0x74, 0x70,
	0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8b, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x72,
	0x65, 0x71, 0x73, 0x32, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2c, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72,
	0x65, 0x71, 0x73, 0x32, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x35,
	0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6b,
	0x61, 0x6e, 0x6f, 0x72, 0x69, 0x79, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x74, 0x61, 0x6e, 0x69, 0x2f,
	0x67, 0x6f, 0x2d, 0x72, 0x65, 0x71, 0x73, 0x32, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reqs2http_v1_request_proto_rawDescOnce sync.Once
	file_reqs2http_v1_request_proto_rawDescData = file_reqs2http_v1_request_proto_rawDesc
)

func file_reqs2http_v1_request_proto_rawDescGZIP() []byte {
	file_reqs2http_v1_request_proto_rawDescOnce.Do(func() {
		file_reqs2http_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_reqs2http_v1_request_proto_rawDescData)
	})
	return file_reqs2http_v1_request_proto_rawDescData
}

var file_reqs2http_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_reqs2http_v1_request_proto_goTypes = []interface{}{
	(*Request)(nil), // 0: reqs2http.v1.Request
	(Method)(0),     // 1: reqs2http.v1.Method
	(*Header)(nil),  // 2: reqs2http.v1.Header
}
var file_reqs2http_v1_request_proto_depIdxs = []int32{
	1, // 0: reqs2http.v1.Request.method:type_name -> reqs2http.v1.Method
	2, // 1: reqs2http.v1.Request.header:type_name -> reqs2http.v1.Header
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reqs2http_v1_request_proto_init() }
func file_reqs2http_v1_request_proto_init() {
	if File_reqs2http_v1_request_proto != nil {
		return
	}
	file_reqs2http_v1_header_proto_init()
	file_reqs2http_v1_method_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_reqs2http_v1_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reqs2http_v1_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reqs2http_v1_request_proto_goTypes,
		DependencyIndexes: file_reqs2http_v1_request_proto_depIdxs,
		MessageInfos:      file_reqs2http_v1_request_proto_msgTypes,
	}.Build()
	File_reqs2http_v1_request_proto = out.File
	file_reqs2http_v1_request_proto_rawDesc = nil
	file_reqs2http_v1_request_proto_goTypes = nil
	file_reqs2http_v1_request_proto_depIdxs = nil
}
